
name: AllThingsEmbedded Builder

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: hadolint/hadolint-action@v1.5.0
      with:
        dockerfile: Dockerfile
        failure-threshold: info
